---
- name: Install Packages
  ansible.builtin.yum: name = {{ item }} state=present
  with_items:
    - python2-pip
    - python-devel
    - gcc
    - python-setuptools
    - rsyslog-kafka

- name: Install Repo Lua & Nginx
  ansible.builtin.yum: name={{ item }} state=present
  with_items:
    - http://repo.glxplay.io/CDN/libmaxminddb-1.2.0-1.el7.x86_64.rpm
    - http://repo.glxplay.io/CDN/luajit-2.1.20190329-1.el7.x86_64.rpm
    - http://repo.glxplay.io/CDN/luajit-devel-2.1.20190329-1.el7.x86_64.rpm
    - http://repo.glxplay.io/CDN/nginx-1.19.6-1.el7.gcdn.x86_64.rpm


- name: Copy SSL certificates
  block:
    - name: Copy SSL certificates
      ansible.builtin.copy:
        src: galaxyplay.vn.pem
        dest: /etc/nginx/ssl/galaxyplay.vn.pem
        owner: root
        mode: 0600
      notify:
        - restart nginx
    
    - name: Copy SSL private key
      ansible.builtin.copy:
        src: galaxyplay.vn.pem
        dest: /etc/nginx/ssl/galaxyplay.vn.pem
        owner: root
        mode: 0600
      notify:
        - restart nginx

- name: Copy nginx.conf
  ansible.builtin.copy:
    src: nginx.conf
    dest: '/etc/nginx/nginx.conf'
    owner: root
    group: root
  notify:
    - restart nginx

- name: start nginx and configure to startup automatically
  service:
    name: nginx
    state: started
    enabled: yes