- name: Base setup
  ansible.builtin.yum:
    name: "{{ item }}"
    state: present
  with_items:
    - vim
    - curl
    - wget
    - git
    - whois
    - telnet
    - htop
    - strace
    - net-tools
    - lsof