- name: Copy sysctl.conf
  ansible.builtin.copy:
    src: sysctl.conf
    dest: /etc/sysctl.conf
    mode: "644"

- name: Apply sysctl config
  ansible.builtin.sysctl:
    name: net.ipv4.ip_forward
    value: "1"
    sysctl_file: /etc/sysctl.conf
    reload: yes