- name: install chrony
  ansible.builtin.yum:
    name: chrony
    state: latest
    
- name: config chronyd
  ansible.builtin.copy:
   src: chrony.conf
   dest: /etc/chrony.conf
   mode: '0644'

- name: Restart chronyd
  ansible.builtin.service:
    name: chronyd
    state: restarted
    enabled: yes
    
- name: Sync time
  ansible.builtin.command: chronyc -a makestep
